# Generated by Django 5.1.7 on 2025-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='surat'),
            preserve_default=False,
        ),
    ]
