# Generated by Django 5.1.7 on 2025-04-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_delete_blog'),
        ('my_app', '0002_icecream'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='icecream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.icecream'),
        ),
    ]
